channels:
  - pytorch
  - anaconda
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip=23.2.1
  - anndata=0.8.0
  - attrs=22.1.0
  - bioconductor-annotate=1.72.0
  - bioconductor-annotationdbi=1.56.2
  - bioconductor-apeglm=1.16.0
  - bioconductor-biobase=2.54.0
  - bioconductor-biocgenerics=0.40.0
  - bioconductor-biocparallel=1.28.3
  - bioconductor-biostrings=2.62.0
  - bioconductor-delayedarray=0.20.0
  - bioconductor-deseq2=1.34.0
  - bioconductor-genefilter=1.76.0
  - bioconductor-geneplotter=1.72.0
  - bioconductor-genomeinfodb=1.30.1
  - bioconductor-genomeinfodbdata=1.2.7
  - bioconductor-genomicranges=1.46.1
  - bioconductor-iranges=2.28.0
  - bioconductor-keggrest=1.34.0
  - bioconductor-matrixgenerics=1.6.0
  - bioconductor-s4vectors=0.32.4
  - bioconductor-summarizedexperiment=1.24.0
  - bioconductor-xvector=0.34.0
  - bioconductor-zlibbioc=1.40.0
  - blas=1.0
  - cudatoolkit=11.1.74
  - cudnn=8.4.1.50
  - curl=7.85.0
  - hdf5=1.12.2
  - ipykernel=5.4.2
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.1
  - jupyterlab_widgets=1.1.1
  - pytest=7.1.2
  - python=3.8.12
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - r=4.1
  - r-acepack=1.4.1
  - r-base=4.1.3
  - r-devtools=2.4.5
  - r-ggplot2=3.4.0
  - r-glue=1.6.2
  - r-plyr=1.8.8
  - r-rcpp=1.0.9
  - r-shiny=1.7.3
  - r-tibble=3.1.8
  - r-utf8=1.2.2
  - r-vctrs=0.5.1
  - r-viridis=0.6.2
  - r-viridislite=0.4.1
  - r-whisker=0.4
  - samtools=1.6
  - scipy=1.6.0
  - setuptools=49.6.0
  - snakemake=7.24.0
  - statsmodels=0.12.1
  - wheel=0.36.2
  - wrapt=1.15.0
  - yaml=0.2.5
  - pybigwig=0.3
  - pip:
      - adjusttext>=0.8
      - auditwheel==5.1.2
      - beautifulsoup4==4.11.1
      - bio==1.5.6
      - biopython==1.81
      - crispr-bean==0.2.5
      - cython==0.29.32
      - h5py==3.7.0
      - jupyter-client==7.3.4
      - jupyter-contrib-core==0.4.2
      - jupyter-contrib-nbextensions==0.7.0
      - jupyter-core==4.11.1
      - jupyter-highlight-selected-word==0.2.0
      - jupyter-nbextensions-configurator==0.6.3
      - jupyter-server==1.18.1
      - jupyter-telemetry==0.1.0
      - jupyterhub==3.1.0
      - jupyterlab==3.4.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.15.0
      - jupyterthemes==0.20.0
      - licorice==0.0.3
      - liftover==1.1.16
      - logomaker==0.8
      - matplotlib==3.7.1
      - nbclassic==0.4.3
      - nbclient==0.6.6
      - nbconvert==6.5.1
      - nbformat==5.4.0
      - nbparameterise==0.6
      - numpy==1.23.1
      - openpyxl==3.0.10
      - pandas==1.4.3
      - papermill==2.4.0
      - pip==23.2.1
      - pipdeptree==2.13.0
      - pipreqs==0.4.11
      - pkginfo==1.8.3
      - pool-sharq==0.0.12
      - pyelftools==0.29
      - pyliftover==0.4
      - pyrequisites==0.0.2
      - pyro-api==0.1.2
      - pytest-order==1.1.0
      - python-slugify==8.0.1
      - regex==2022.7.25
      - scikit-learn==1.3.0
      - seaborn==0.12.1
      - seqspec==0.0.0
      - sklearn==0.0.post7
      - torch==1.12.1
      - tqdm==4.64.0
      - twine==4.0.1
      - typing-extensions==4.3.0
      - werkzeug==2.2.3
      - xgboost==1.7.5
